services:
  - type: worker
    name: email-service
    env: go
    buildCommand: go build -tags musl --ldflags '-linkmode external -extldflags "-static"' -o /app/app .
    startCommand: /app/app
    build:
      dockerfilePath: ./Dockerfile
